### ISSUE TITLE
OpenSSL certificate expired in "make check"

### ISSUE THREAD

**Issue by noahgibbs** [vnmakarov/ruby#9]
I'm seeing OpenSSL failures when building this branch, but I don't see them when building current trunk Ruby on the same EC2 instance - maybe one or more missing commits?

Here's what I'm seeing a bunch of:

```
 19) Failure:
TestNetHTTPS#test_session_reuse_but_expire [/home/ubuntu/stack-rtl-mjit/test/net/http/utils.rb:48]:
<[]> expected but was
<["[2019-02-19 20:04:45] ERROR OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=unknown state: sslv3 alert certificate expired\n" +
 "\t/home/ubuntu/stack-rtl-mjit/lib/webrick/server.rb:299:in `accept'\n" +
 "\t/home/ubuntu/stack-rtl-mjit/lib/webrick/server.rb:299:in `block (2 levels) in start_thread'\n" +
 "\t/home/ubuntu/stack-rtl-mjit/lib/webrick/utils.rb:263:in `timeout'\n" +
 "\t/home/ubuntu/stack-rtl-mjit/lib/webrick/server.rb:297:in `block in start_thread'\n"]>.
```

**Comment by vnmakarov** [comment]
Noah, thank you for reporting.  I see stack-rtl-mjit-base (a trunk at some point in Dec) has the same problem.  I think the next round of merge with trunk would solve the problem.  I've chosen a wrong version of trunk to merge with.  I should have been more careful with choosing a merge point.
